apiVersion: v1
kind: Namespace
metadata:
  name: openshift-authentication-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"
