apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: kube-scheduler
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    exclude.release.openshift.io/internal-openshift-hosted: "true"
spec: {}
status:
  versions:
  - name: operator
    version: "4.6.36"
  - name: raw-internal
    version: "4.6.36"
  - name: kube-scheduler
    version: "1.19.4"
  relatedObjects:
    - group: operator.openshift.io
      name: cluster
      resource: kubeschedulers
    - group: config.openshift.io
      resource: schedulers
    - group: ""
      name: openshift-config
      resource: namespaces
    - group: ""
      name: openshift-config-managed
      resource: namespaces
    - group: ""
      name: openshift-kube-scheduler-operator
      resource: namespaces
    - group: ""
      name: openshift-kube-scheduler
      resource: namespaces
    - group: controlplane.operator.openshift.io
      resource: podnetworkconnectivitychecks
      namespace: openshift-kube-scheduler
