apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: csi-snapshot-controller
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
status:
  versions:
  - name: operator
    version: "4.6.36"
  - name: csi-snapshot-controller
    version: "4.6.36"
spec: {}
