apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: openshift-apiserver-operator
  name: openshift-apiserver-operator
  labels:
    app: openshift-apiserver-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    exclude.release.openshift.io/internal-openshift-hosted: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: openshift-apiserver-operator
  template:
    metadata:
      name: openshift-apiserver-operator
      labels:
        app: openshift-apiserver-operator
    spec:
      serviceAccountName: openshift-apiserver-operator
      containers:
      - name: openshift-apiserver-operator
        terminationMessagePolicy: FallbackToLogsOnError
        image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:6efc3e16de7dbdf97daec51eb5666b8041646b4144f2d0acd559988272d0216e
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8443
          name: metrics
          protocol: TCP
        command: ["cluster-openshift-apiserver-operator", "operator"]
        args:
        - "--config=/var/run/configmaps/config/config.yaml"
        resources:
          requests:
            memory: 50Mi
            cpu: 10m
        volumeMounts:
        - mountPath: /var/run/configmaps/config
          name: config
        - mountPath: /var/run/secrets/serving-cert
          name: serving-cert
        env:
        - name: IMAGE
          value: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:f165bb02bf3fbf3430a2a3c47efcbdfc24295370c152d6822283d1ec8067bbe2
        - name: OPERATOR_IMAGE
          value: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:6efc3e16de7dbdf97daec51eb5666b8041646b4144f2d0acd559988272d0216e
        - name: OPERATOR_IMAGE_VERSION
          value: "4.6.36"
        - name: OPERAND_IMAGE_VERSION
          value: "4.6.36"
        - name: KUBE_APISERVER_OPERATOR_IMAGE
          value: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:17db5d16be43603c2e8255ba98dc7cb8f53a3e10c8fbbf644602b707cc797f2e
      volumes:
      - name: serving-cert
        secret:
          secretName: openshift-apiserver-operator-serving-cert
          optional: true
      - name: config
        configMap:
          name: openshift-apiserver-operator-config
      nodeSelector:
        node-role.kubernetes.io/master: ""
      priorityClassName: "system-cluster-critical"
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 120
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 120
