apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: openshift-kube-scheduler-operator
  name: openshift-kube-scheduler-operator
  labels:
    app: openshift-kube-scheduler-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    exclude.release.openshift.io/internal-openshift-hosted: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openshift-kube-scheduler-operator
  template:
    metadata:
      name: openshift-kube-scheduler-operator
      labels:
        app: openshift-kube-scheduler-operator
    spec:
      serviceAccountName: openshift-kube-scheduler-operator
      containers:
      - name: kube-scheduler-operator-container
        image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:45a47c7a49b1cd084944e4e69b8259c7458f0713236d2fc81096b4be0848d0e3
        imagePullPolicy: IfNotPresent
        command: ["cluster-kube-scheduler-operator", "operator"]
        args:
        - "--config=/var/run/configmaps/config/config.yaml"
        - "-v=2"
        resources:
          requests:
            memory: 50Mi
        volumeMounts:
        - mountPath: /var/run/configmaps/config
          name: config
        - mountPath: /var/run/secrets/serving-cert
          name: serving-cert
        env:
        - name: IMAGE
          value: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:745173c0b0fc62cfa10cead1e93f0aebdc382063f67c5ad16999e25c177be11d
        - name: OPERATOR_IMAGE
          value: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:45a47c7a49b1cd084944e4e69b8259c7458f0713236d2fc81096b4be0848d0e3
        - name: OPERATOR_IMAGE_VERSION
          value: "4.6.36"
        - name: OPERAND_IMAGE_VERSION
          value: "1.19.4"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name          
        terminationMessagePolicy: FallbackToLogsOnError
      volumes:
      - name: serving-cert
        secret:
          secretName: kube-scheduler-operator-serving-cert
          optional: true
      - name: config
        configMap:
          name: openshift-kube-scheduler-operator-config
      nodeSelector:
        node-role.kubernetes.io/master: ""
      priorityClassName: system-cluster-critical
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 120
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 120
  
