kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-storage-operator-role
  namespace: openshift-cluster-storage-operator
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
  - kind: ServiceAccount
    name: cluster-storage-operator
    namespace: openshift-cluster-storage-operator
roleRef:
  # TODO: rework to smaller roles
  kind: ClusterRole
  name: cluster-admin
