apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: openshift-user-critical
value: 1000000000
globalDefault: false
description: "This priority class should be used for user facing OpenShift workload pods only."
