apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: openshift-kube-storage-version-migrator-operator
  name: kube-storage-version-migrator-operator
  labels:
    app: kube-storage-version-migrator-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kube-storage-version-migrator-operator
  template:
    metadata:
      name: kube-storage-version-migrator-operator
      labels:
        app: kube-storage-version-migrator-operator
    spec:
      serviceAccountName: kube-storage-version-migrator-operator
      containers:
      - name: kube-storage-version-migrator-operator
        terminationMessagePolicy: FallbackToLogsOnError
        image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:bac953b5c6978c80f4a1dd7b23746a001948f22d619f6a1f09e590aa538db0e0
        ports:
        - containerPort: 8443
          name: metrics
          protocol: TCP
        command: ["cluster-kube-storage-version-migrator-operator", "start"]
        args:
          - "--config=/var/run/configmaps/config/config.yaml"
        resources:
          requests:
            memory: 50Mi
            cpu: 10m
        volumeMounts:
          - mountPath: /var/run/configmaps/config
            name: config
          - mountPath: /var/run/secrets/serving-cert
            name: serving-cert
        env:
        - name: IMAGE
          value: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:5da82b0e80b6087ac1f0361fa64d019750129eb0340b93e140f6450bf8baba7d
        - name: OPERATOR_IMAGE
          value: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:bac953b5c6978c80f4a1dd7b23746a001948f22d619f6a1f09e590aa538db0e0
        - name: OPERATOR_IMAGE_VERSION
          value: "4.6.36"
        - name: OPERAND_IMAGE_VERSION
          value: "4.6.36"
      volumes:
        - name: serving-cert
          secret:
            secretName: serving-cert
            optional: true
        - name: config
          configMap:
            name: config
      nodeSelector:
        node-role.kubernetes.io/master: ""
      priorityClassName: "system-cluster-critical"
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 120
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 120
