apiVersion: helm.openshift.io/v1beta1
kind: HelmChartRepository
metadata:
  annotations:
    "release.openshift.io/create-only": 'true'
  name: redhat-helm-repo
spec:
  name: Red Hat Helm Charts
  connectionConfig:
    url: https://redhat-developer.github.io/redhat-helm-charts
