apiVersion: v1
kind: ConfigMap
metadata:
  name: machine-config-osimageurl
  namespace: openshift-machine-config-operator
data:
  releaseVersion: 4.6.36
  # The OS payload, managed by the daemon + pivot + rpm-ostree
  # https://github.com/openshift/machine-config-operator/issues/183
  osImageURL: "quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:da624f8006e58abcec78bb926be1365a9bf1084d1835796322af9ff44c4d7295"
