apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: openshift-authentication-operator
  name: authentication-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
  labels:
    app: authentication-operator
